name: ComeFeliz
favicon: null
layout_spectrum: 0.2028691191226244
typography_spectrum: 0.32363630877807736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2422309264075011
  lightness: 0.2794906988274306
  saturation: 0.6855582834687084
  rhythmicContrast: 0.9486309757921845
purpose: []
